name: fantasy_drum_corps
description: Fantasy sports inspired Drum Corps game

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  flutter_riverpod: ^2.2.0
  cloud_firestore: ^4.4.3
  google_sign_in: ^6.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^6.0.10
  flex_color_scheme: ^6.1.2
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  email_validator: ^2.1.17
  shared_preferences: ^2.0.18
  uuid: ^3.0.7
  profanity_filter: ^2.0.0
  file_picker: ^5.2.5
  firebase_storage: ^11.0.14
  socket_io_client: ^2.0.1
  json_annotation: ^4.8.0
  responsive_framework: ^0.2.0
  mime: ^1.0.4
  riverpod_annotation: ^2.0.2
  quiver: ^3.2.1
  build_runner: ^2.3.3
  fluttermoji: ^1.0.2
  flutter_svg: ^2.0.4
  get: ^4.6.5
  round_icon: ^0.0.4


dev_dependencies:
  json_serializable: ^6.6.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.1.4
  mocktail: ^0.3.0
  riverpod_lint: ^1.1.6
  custom_lint: ^0.3.2

flutter:
  generate: true
  assets:
    - assets/

  uses-material-design: true

