// Mocks generated by Mockito 5.3.2 from annotations
// in fantasy_drum_corps/test/src/features/players/domain/player_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:fantasy_drum_corps/src/features/fantasy_corps/domain/drum_corps_enum.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'player_model_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MockPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockPlayer extends _i1.Mock implements _i2.MockPlayer {
  MockMockPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get playerId => (super.noSuchMethod(
        Invocation.getter(#playerId),
        returnValue: '',
      ) as String);
  @override
  set displayName(String? _displayName) => super.noSuchMethod(
        Invocation.setter(
          #displayName,
          _displayName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set about(String? _about) => super.noSuchMethod(
        Invocation.setter(
          #about,
          _about,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set selectedCorps(_i3.DrumCorps? _selectedCorps) => super.noSuchMethod(
        Invocation.setter(
          #selectedCorps,
          _selectedCorps,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set photoUrl(String? _photoUrl) => super.noSuchMethod(
        Invocation.setter(
          #photoUrl,
          _photoUrl,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
