enum DrumCorps {
    theAcademy = 'The Academy',
    blueDevils = 'Blue Devils',
    blueKnights = 'Blue Knihts',
    blueStars = 'Blue Stars',
    bluecoats = 'Bluecoats',
    bostonCrusaders = 'Boston Crusaders',
    theCadets = 'The Cadets',
    carolinaCrown = 'Carolina Crown',
    theCavaliers = 'The Cavaliers',
    colts = 'The Colts',
    crossmen = 'Crossmen',
    genesis = 'Genesis',
    jerseySurf = 'Jersey Surf',
    madisonScouts = 'Madison Scouts',
    mandarins = 'Mandarins',
    musicCity = 'Music City',
    pacificCrest = 'Pacific Crest',
    phantomRegiment = 'Phantom Regiment',
    santaClaraVanguard = 'Santa Clara Vanguard',
    seattleCascades = 'Seattle Cascades',
    spiritOfAtlanta = 'Spirit of Atlanta',
    troopers = 'Troopers',
  }